#! /bin/sh
killall -q dunst & 
picom &
killall -q sxhkd &
sxhkd -c .config/sxhkd/sxhkdrc &
pgrep -x sxhkd > /dev/null || sxhkd &
dunst &

bspc monitor HDMI-0 -d I & 
bspc monitor HDMI-1 -d II &

bspc config border_width         2
bspc config window_gap          12
bspc config border_radius       15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

setxkbmap -layout us,ru -option grp:ctrl_shift_toggle &

feh --bg-scale ~/Pictures/wallpaper.jpg &
$HOME/.config/polybar/launch.sh &
